# Build stage
FROM node:22-alpine AS builder

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Define build arguments
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG UPLINK_SUPABASE_URL
ARG UPLINK_SUPABASE_KEY
ARG UPLINK_SUPABASE_SERVICE_ROLE_KEY
ARG BASE_RPC_URL
ARG MAINNET_RPC_URL
ARG ARBITRUM_RPC_URL
# ARG OPTIMISM_RPC_URL
# ARG SONIC_RPC_URL
ARG MAINNET_ETHERFI_RPC_URL
ARG MAINNET_LIDO_RPC_URL
# ARG MAINNET_GHO_RPC_URL
# ARG MODE_RPC_URL

# Set environment variables
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV BASE_RPC_URL=$BASE_RPC_URL
ENV MAINNET_RPC_URL=$MAINNET_RPC_URL
ENV ARBITRUM_RPC_URL=$ARBITRUM_RPC_URL
# ENV OPTIMISM_RPC_URL=$OPTIMISM_RPC_URL
# ENV SONIC_RPC_URL=$SONIC_RPC_URL
ENV MAINNET_ETHERFI_RPC_URL=$MAINNET_ETHERFI_RPC_URL
ENV MAINNET_LIDO_RPC_URL=$MAINNET_LIDO_RPC_URL
# ENV MAINNET_GHO_RPC_URL=$MAINNET_GHO_RPC_URL
# ENV MODE_RPC_URL=$MODE_RPC_URL
ENV UPLINK_SUPABASE_URL=$UPLINK_SUPABASE_URL
ENV UPLINK_SUPABASE_KEY=$UPLINK_SUPABASE_KEY
ENV UPLINK_SUPABASE_SERVICE_ROLE_KEY=$UPLINK_SUPABASE_SERVICE_ROLE_KEY
# Copy package files
COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .
RUN pnpm build
# The build process now automatically copies assets from src/public to public

# Production stage
FROM node:22-alpine

WORKDIR /app

# Install pnpm globally
RUN npm install -g pnpm

# Define build arguments again for the production stage
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG BASE_RPC_URL
ARG MAINNET_RPC_URL
ARG ARBITRUM_RPC_URL
ARG MAINNET_ETHERFI_RPC_URL
ARG MAINNET_LIDO_RPC_URL
ARG UPLINK_SUPABASE_URL
ARG UPLINK_SUPABASE_KEY
ARG UPLINK_SUPABASE_SERVICE_ROLE_KEY

# Set environment variables
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_KEY=$SUPABASE_KEY
ENV BASE_RPC_URL=$BASE_RPC_URL
ENV MAINNET_RPC_URL=$MAINNET_RPC_URL
ENV ARBITRUM_RPC_URL=$ARBITRUM_RPC_URL
ENV MAINNET_ETHERFI_RPC_URL=$MAINNET_ETHERFI_RPC_URL
ENV MAINNET_LIDO_RPC_URL=$MAINNET_LIDO_RPC_URL
ENV UPLINK_SUPABASE_URL=$UPLINK_SUPABASE_URL
ENV UPLINK_SUPABASE_KEY=$UPLINK_SUPABASE_KEY
ENV UPLINK_SUPABASE_SERVICE_ROLE_KEY=$UPLINK_SUPABASE_SERVICE_ROLE_KEY
# Copy package files
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod

# Copy built application
COPY --from=builder /app/dist ./dist

# Copy static files - these are now already copied to /public during build
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["node", "dist/main"] 