name: Deploy to ECS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
      ECS_CLUSTER_NAME: ai-api
      ECS_SERVICE_NAME: ai-api-service

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v2

      - name: Install or Update AWS CLI v2
        run: |
          if [ -f "/usr/local/aws-cli/v2/current/bin/aws" ]; then
            echo "AWS CLI is already installed. Updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && aws configure set default.region $AWS_DEFAULT_REGION

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo usermod -aG docker $USER
    
      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 \
            --build-arg SUPABASE_URL=${{ secrets.SUPABASE_API_URL }} \
            --build-arg SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
            --build-arg BASE_RPC_URL=${{ secrets.BASE_RPC_URL }} \
            --build-arg MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} \
            --build-arg ARBITRUM_RPC_URL=${{ secrets.ARBITRUM_RPC_URL }} \
            --build-arg MAINNET_ETHERFI_RPC_URL=${{ secrets.MAINNET_ETHERFI_RPC_URL }} \
            --build-arg MAINNET_LIDO_RPC_URL=${{ secrets.MAINNET_LIDO_RPC_URL }} \
            --build-arg UPLINK_SUPABASE_URL=${{ secrets.UPLINK_SUPABASE_URL }} \
            --build-arg UPLINK_SUPABASE_KEY=${{ secrets.UPLINK_SUPABASE_KEY }} \
            --build-arg UPLINK_SUPABASE_SERVICE_ROLE_KEY=${{ secrets.UPLINK_SUPABASE_SERVICE_ROLE_KEY }} \
            -t api/api-mcp-builds .
          docker images

      - name: Push Image to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264122535.dkr.ecr.us-east-1.amazonaws.com
          docker tag api/api-mcp-builds:latest 058264122535.dkr.ecr.us-east-1.amazonaws.com/api/api-mcp-builds:latest
          docker push 058264122535.dkr.ecr.us-east-1.amazonaws.com/api/api-mcp-builds:latest

      - name: Update Infra with latest deployment
        id: update_infra
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment

      - name: Check deployment status
        if: steps.update_infra.outcome != 'success'
        run: |
          echo "Deployment failed"
          exit 1

      - name: Wait for service stability
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER_NAME \
            --services $ECS_SERVICE_NAME

      - name: Finalize
        if: steps.update_infra.outcome == 'success'
        run: echo "Deployment completed successfully"